services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./api:/data/www:consistent
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      
  php-fpm:
    build:
      context: docker/php
    volumes:
      - ./api:/data/www:consistent

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS:-toor}
      MYSQL_DATABASE: ${DATABASE:-sample}
      MYSQL_USER: ${MYSQL_USER:-john}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-johnPass}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mysql_data: