nelmio_api_doc:
  documentation:
    info:
      title: Sample Company app
      description: Sample app to show how Symfony can be used to create a DDD application
      version: 1.0.0
  areas:
    path_patterns:
      - ^/api(?!/doc$)
      - ^/worker(.*)$
      - ^/company(.*)$